package marshalling

// this code is generated by go generate
// DO NOT EDIT!

import (
	"tag-names/model"

	"fmt"
	"time"
)

func MarshalTrade(object model.Trade) string {
	return fmt.Sprintf("id:%d\ndate_time:%s\nsymbol:%s\nprice:%.2f\namount:%.2f\n", object.Id, object.DateTime.Format(time.RFC3339), object.Symbol, object.Price, object.Amount)
}
